src/TravelBlog/Models/Experience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TravelBlog.Models
{
    [Table("Experiences")]
    public class Experience
    {
        [Key]
        public int ExperienceId { get; set; }
        public string Title { get; set; }
        public int LocationId { get; set; }
        public string ImageURL { get; set; }
        public string Description { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<PeopleExperience> PeopleExperiences { get; set; }
    }
}

src/TravelBlog/Controllers/ExperiencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelBlog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace TravelBlog.Controllers
{
    public class ExperiencesController : Controller
    {
        private TravelBlogDbContext db = new TravelBlogDbContext();
        public IActionResult Index()
        {
            return View(db.Experiences.Include(experiences => experiences.Location).ToList());
        }
        public IActionResult Details(int id)
        {
            var thisExperience = db.Experiences
                .Include(experiences => experiences.Location)
                .Include(experiences => experiences.PeopleExperiences)
                .ThenInclude(experiences => experiences.People)
                .FirstOrDefault(experiences=>experiences.ExperienceId == id);
            return View(thisExperience);
        }
        public IActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "CityName");
            ViewBag.PersonId = new SelectList(db.Peoples, "PersonId", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Experience experience, People person)
        {
            db.Experiences.Add(experience);
            var newPeopleExperience = new PeopleExperience{  PersonId = person.PersonId, ExperienceId = experience.ExperienceId };
            db.PeopleExperiences.Add(newPeopleExperience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "CityName");
            return View(thisExperience);
        }
        [HttpPost]
        public IActionResult Edit(Experience experience)
        {
            db.Entry(experience).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            return View(thisExperience);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            db.Experiences.Remove(thisExperience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TravelBlog/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelBlog.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TravelBlog.Controllers
{
    public class LocationsController : Controller
    {
        private ILocationRepository locationRepo;

        public LocationsController(ILocationRepository thisRepo = null)
        {
            if (thisRepo == null)
            {
                this.locationRepo = new EFLocationRepository();
            }
            else
            {
                this.locationRepo = thisRepo;
            }
        }


        public IActionResult Index()
        {
            return View(locationRepo.Locations.ToList());
        }

        public IActionResult Details(int id)
        {
            var thisLocation = locationRepo.Locations
                .Include(locations => locations.Experiences)
                .FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Location location)
        {
            locationRepo.Save(location);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        [HttpPost]
        public IActionResult Edit(Location location)
        {
            locationRepo.Edit(location);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            locationRepo.Remove(thisLocation);
            return RedirectToAction("Index");
        }

    }
}

src/TravelBlog/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelBlog.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TravelBlog.Controllers
{
    public class PeoplesController : Controller
    {
        private TravelBlogDbContext db = new TravelBlogDbContext();
        public IActionResult Index()
        {
            return View(db.Peoples.ToList());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            
            var thisPeople = db.Peoples
                .Include(peoples => peoples.PeopleExperiences)
                .ThenInclude(peoples => peoples.Experience)
                .FirstOrDefault(peoples => peoples.PersonId == id);
            var experiences = thisPeople.PeopleExperiences.Select(pe => pe.Experience).ToList();
            //var model = new Dictionary<string, object>;
            //model.Add("people", thisPeople);
            //model.Add("experiences", experiences);
            foreach(PeopleExperience pE in thisPeople.PeopleExperiences)
            {
                Console.WriteLine(pE.Experience.Title);
            }
            return View(thisPeople);
        }

        public IActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "CityName");
            return View();
        }

        [HttpPost]
        public IActionResult Create(People people)
        {
            db.Peoples.Add(people);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisPeople = db.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            return View(thisPeople);
        }

        [HttpPost]
        public IActionResult Edit(People people)
        {
            db.Entry(people).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisPeople = db.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            return View(thisPeople);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisPeople = db.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            db.Peoples.Remove(thisPeople);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

src/TravelBlog/Views/Experiences/Create.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create a new experience</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.LabelFor(model => model.Location)
    @Html.DropDownList("LocationId")

    @Html.LabelFor(model => model.PeopleExperiences)
    @Html.DropDownList("PersonId")

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.ImageURL)
    @Html.EditorFor(model => model.ImageURL)

    <input type="submit" value="Create" class="btn btn-default" />
}

@Html.ActionLink("Back to List", "Index")

src/TravelBlog/Views/Experiences/Delete.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to delete this?</h2>
<hr />
@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

src/TravelBlog/Views/Experiences/Details.cshtml
@model TravelBlog.Models.Experience

@{ 
    ViewData["Title"] = "Experience - Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Experience Details</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <img src="@Model.ImageURL" class="location-image" />
    </div>
    <div class="col-md-8">
        <p>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)</p>
        <p>City, Country: @Html.DisplayFor(model => model.Location.CityName), @Html.DisplayFor(model => model.Location.Country)</p>


        <p>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</p>
        <h3>People:</h3>
        <ul>
            @foreach (var people in Model.PeopleExperiences)
            {

                <li> @Html.ActionLink(people.People.Name, "Details", "Peoples", new { id = people.PersonId }) </li>
            }
        </ul>
    </div>
    <div class="col-md-12">
        <p>@Html.ActionLink("Edit", "Edit", new { id = Model.ExperienceId })</p>
    </div>
</div>

src/TravelBlog/Views/Experiences/Edit.cshtml
@model TravelBlog.Models.Experience

@{
    ViewData["Title"] = "Experience - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
<hr />
<h4>Edit this experience: @Html.DisplayFor(model => model.Title)</h4>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ExperienceId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)

    @Html.LabelFor(model => model.Location)
    @Html.DropDownList("LocationId")

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.ImageURL)
    @Html.EditorFor(model => model.ImageURL)


    <input type="submit" value="Save" class="btn btn-default" />
}
@Html.ActionLink("Back to List", "Index")

src/TravelBlog/Views/Experiences/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<TravelBlog.Models.Experience>

<div class="container">
    <h2>Travel Blog</h2>
    <hr />

    <ul>
        @foreach (var listExperience in Model)
        {
            <li>@Html.ActionLink(listExperience.Title, "Details", new { id = listExperience.ExperienceId }) | @Html.ActionLink("Edit", "Edit", new { id = listExperience.ExperienceId }) | @Html.ActionLink("Delete", "Delete", new { id = listExperience.ExperienceId })</li>
        }
    </ul>
    <p>@Html.ActionLink("Create New", "Create") | @Html.ActionLink("Back to Locations", "Index", "Locations")</p>
</div>