src/TravelBlog/Controllers/ExperiencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelBlog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace TravelBlog.Controllers
{
    public class ExperiencesController : Controller
    {
        private TravelBlogDbContext db = new TravelBlogDbContext();
        public IActionResult Index()
        {
            return View(db.Experiences.Include(experiences => experiences.Location).ToList());
        }
        public IActionResult Details(int id)
        {
            var thisExperience = db.Experiences
                .Include(experiences => experiences.Location)
                .Include(experiences => experiences.PeopleExperiences)
                .ThenInclude(experiences => experiences.People)
                .FirstOrDefault(experiences=>experiences.ExperienceId == id);
            return View(thisExperience);
        }
        public IActionResult Create()
        {
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "CityName");
            ViewBag.PersonId = new SelectList(db.Peoples, "PersonId", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Experience experience, People person)
        {
            db.Experiences.Add(experience);
            var newPeopleExperience = new PeopleExperience{  PersonId = person.PersonId, ExperienceId = experience.ExperienceId };
            db.PeopleExperiences.Add(newPeopleExperience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "CityName");
            return View(thisExperience);
        }
        [HttpPost]
        public IActionResult Edit(Experience experience)
        {
            db.Entry(experience).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            return View(thisExperience);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisExperience = db.Experiences.FirstOrDefault(experiences => experiences.ExperienceId == id);
            db.Experiences.Remove(thisExperience);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TravelBlog/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelBlog.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TravelBlog.Controllers
{
    public class LocationsController : Controller
    {
        private ILocationRepository locationRepo;

        public LocationsController(ILocationRepository thisRepo = null)
        {
            if (thisRepo == null)
            {
                this.locationRepo = new EFLocationRepository();
            }
            else
            {
                this.locationRepo = thisRepo;
            }
        }


        public IActionResult Index()
        {
            return View(locationRepo.Locations.ToList());
        }

        public IActionResult Details(int id)
        {
            var thisLocation = locationRepo.Locations
                .Include(locations => locations.Experiences)
                .FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Location location)
        {
            locationRepo.Save(location);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        [HttpPost]
        public IActionResult Edit(Location location)
        {
            locationRepo.Edit(location);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            return View(thisLocation);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisLocation = locationRepo.Locations.FirstOrDefault(locations => locations.LocationId == id);
            locationRepo.Remove(thisLocation);
            return RedirectToAction("Index");
        }

    }
}

src/TravelBlog/Controllers/PeoplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelBlog.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TravelBlog.Controllers
{
    public class PeoplesController : Controller
    {
        private IPeopleRepository peopleRepo;
        private ILocationRepository locationRepo;

        public PeoplesController(IPeopleRepository thisRepo = null, ILocationRepository thisLocationRepo = null)
        {
            if (thisRepo == null)
            {
                this.peopleRepo = new EFPeopleRepository();
            }
            else
            {
                this.peopleRepo = thisRepo;
            }

            if (thisLocationRepo == null)
            {
                this.locationRepo = new EFLocationRepository();
            }
            else
            {
                this.locationRepo = thisLocationRepo;
            }
        }

        public IActionResult Index()
        {
            return View(peopleRepo.Peoples.ToList());
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            
            var thisPeople = peopleRepo.Peoples
                .Include(peoples => peoples.PeopleExperiences)
                .ThenInclude(peoples => peoples.Experience)
                .FirstOrDefault(peoples => peoples.PersonId == id);
            var experiences = thisPeople.PeopleExperiences.Select(pe => pe.Experience).ToList();
            //var model = new Dictionary<string, object>;
            //model.Add("people", thisPeople);
            //model.Add("experiences", experiences);
            foreach(PeopleExperience pE in thisPeople.PeopleExperiences)
            {
                Console.WriteLine(pE.Experience.Title);
            }
            return View(thisPeople);
        }

        public IActionResult Create()
        {
            ViewBag.LocationId = new SelectList(locationRepo.Locations, "LocationId", "CityName");
            return View();
        }

        [HttpPost]
        public IActionResult Create(People people)
        {
            peopleRepo.Save(people);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisPeople = peopleRepo.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            return View(thisPeople);
        }

        [HttpPost]
        public IActionResult Edit(People people)
        {
            peopleRepo.Edit(people);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisPeople = peopleRepo.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            return View(thisPeople);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisPeople = peopleRepo.Peoples.FirstOrDefault(peoples => peoples.PersonId == id);
            peopleRepo.Remove(thisPeople);
            return RedirectToAction("Index");
        }

    }
}

src/TravelBlog/Views/Peoples/Create.cshtml
@model TravelBlog.Models.People

@{
    ViewData["Title"] = "People - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create a new person</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.PeopleLocations)
    @Html.DropDownList("LocationId")

    @Html.LabelFor(model => model.Bio)
    @Html.EditorFor(model => model.Bio)

    @Html.LabelFor(model => model.ImageURL)
    @Html.EditorFor(model => model.ImageURL)

    <input type="submit" value="Create" class="btn btn-default" />
}

@Html.ActionLink("Back to List", "Index")

src/TravelBlog/Views/Peoples/Delete.cshtml
@model TravelBlog.Models.People

@{
    ViewData["Title"] = "People - Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Are you sure you want to delete this?</h2>
<hr />
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

src/TravelBlog/Views/Peoples/Details.cshtml
@model TravelBlog.Models.People

@{ 
    ViewData["Title"] = "People - Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>People Details</h2>
<hr />
<h1>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h1>

<div class="row">
    <div class="col-md-4">
        <img src="@Model.ImageURL" class="avatar-image" />
    </div>
    <div class="col-md-8">
        <p>@Html.DisplayNameFor(model => model.Bio): @Html.DisplayFor(model => model.Bio)</p>

        <h4>Experiences:</h4>
        <ul>
            @if (Model.PeopleExperiences.Count == 0)
            {
                <li>No Experiences Yet</li>
            }
            else
            {
                @foreach (var experience in Model.PeopleExperiences)
                {

                    <li> @Html.ActionLink(experience.Experience.Title, "Details", "Experiences", new { id = experience.ExperienceId }) </li>
                }
            }
        </ul>
    </div>
    <div class="col-md-12">
        <p>@Html.ActionLink("Edit", "Edit", new { id = Model.PersonId })</p>
    </div>
 </div>

src/TravelBlog/Views/Peoples/Edit.cshtml
@model TravelBlog.Models.People

@{
    ViewData["Title"] = "People - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
<hr />
<h4>Edit this person: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.PersonId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.PeopleLocations)
    @Html.DropDownList("LocationId")

    @Html.LabelFor(model => model.Bio)
    @Html.EditorFor(model => model.Bio)

    @Html.LabelFor(model => model.ImageURL)
    @Html.EditorFor(model => model.ImageURL)


    <input type="submit" value="Save" class="btn btn-default" />
}
@Html.ActionLink("Back to List", "Index")

src/TravelBlog/Views/Peoples/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<TravelBlog.Models.People>

<div class="container">
    <h2>Travel Blog</h2>
    <hr />

    <ul>
        @foreach (var listPeople in Model)
        {
            <li>@Html.ActionLink(listPeople.Name, "Details", new { id = listPeople.PersonId }) | @Html.ActionLink("Edit", "Edit", new { id = listPeople.PersonId }) | @Html.ActionLink("Delete", "Delete", new { id = listPeople.PersonId })</li>
        }
    </ul>
    <p>@Html.ActionLink("Create New", "Create") | @Html.ActionLink("Back to Locations", "Index", "Locations")</p>
</div>